---
title: "Tidy Template"
author: "Fabio Votta"
date: "The Date"
output: html_document
---

This script is about:



## Packages and Folders

```{r}
# Install these packages if you don't have them yet
# if (!require("pacman")) install.packages("pacman")
# devtools::install_github("favstats/tidytemplate")

# devtools::install_github("UrbanInstitute/urbnmapr")


pacman::p_load(tidyverse, urbnmapr, rvest)

# Creates folders
# tidytemplate::data_dir()
# tidytemplate::images_dir()
```


## Load Data

```{r, data}
elex <- read_csv("https://raw.githubusercontent.com/favstats/USElection2020-NYT-Results/master/data/latest/presidential.csv")


counties_sf <- get_urbn_map("counties", sf = TRUE)

# election_results <- read_csv(paste0("data/", real_time, "/results_president.csv"))


alaska_fips <- counties_sf %>% 
  filter(state_name == "Alaska") %>% 
  pull(county_fips) 

elex_alaska <- elex %>% 
  filter(state == "alaska") %>% 
  mutate_at(vars(contains("vote"), contains("result"), reporting, precincts), ~sum(.x, na.rm = T)) %>% 
  mutate_at(vars(eevp, margin2020), ~mean(.x, na.rm = T)) %>% 
  mutate(name = "Alaska",
         eevp_value = paste0(eevp, "%"),
         eevp_display = paste0(eevp, "% reported"),
         leader_margin_value =  abs(margin2020),
         leader_margin_display =  ifelse(margin2020 > 0, paste0("R+", round(leader_margin_value)),  paste0("D+", round(leader_margin_value))),
         leader_margin_name_display =  ifelse(margin2020 > 0, paste0("Trump +",round(leader_margin_value)),  paste0("Biden +", round(leader_margin_value))),
         leader_party_id =  ifelse(margin2020 > 0, "republican", "democrat"))  %>% 
  slice(1:length(alaska_fips)) %>% 
  mutate(fips = alaska_fips) 

elex <- elex  %>% 
  filter(state != "alaska") %>% 
  bind_rows(elex_alaska) %>% 
  mutate(trump_perc = results_trumpd/votes*100,
         biden_perc = results_bidenj/votes*100,
         kanye_perc = results_westk/votes*100) %>% 
  rename(county_fips = fips)



counties_sf %>% 
  left_join(elex) %>% 
  mutate(abs_margin2020 = abs(margin2020)) %>% 
  ggplot(aes(fill = margin2016)) +
  geom_sf(aes(alpha = abs_margin2020), color = NA) +
  scale_fill_gradient2(low = "blue", mid = "purple", high = "red") +
  theme_void() +
  scale_alpha(range = c(0.8, 1), guide = "none")
```



```{r, data}
library(ggtext)


counties_sf %>% 
  left_join(elex) %>% 
  mutate(abs_margin2020 = abs(margin2020)) %>% 
  ggplot(aes(fill = margin2020)) +
  geom_sf(aes(alpha = abs_margin2020), 
          color = NA)   +
  geom_sf(data = get_urbn_map("states", sf = T), color = "black", inherit.aes = F, fill = NA) +
  scale_fill_gradient2("Margins", 
                       low = "#0000ff", 
                       mid = "purple", 
                       high = "#ff0803",
                       labels = c("+50% Biden", "0%", "+50% Trump"),
                       breaks = c(-50, 0, 50)) +
  theme_void() +
  scale_alpha(range = c(0.75, 1), guide = "none") +
  labs(title = "**Preliminary** Results of US 2020 Election", 
       subtitle = "Note: In many counties votes are still being counted.\n",
       caption = glue::glue("\nSource: New York Times. Last updated: {as.character(elex$retrieved_time)[1]}. Visualization created by @favstats\n")) +
  theme(plot.title = element_markdown(hjust = 0.5, lineheight = 1.2), 
        plot.subtitle = element_text(hjust = 0.5),
        legend.position = "top") +
  guides(fill = guide_colourbar(direction = "horizontal",
                                label.position = "bottom",
                                barwidth  = 18,
                                barheight = 0.8,  
                                title.vjust = 0.9))

tidytemplate::ggsave_it(us2020map, width = 8, height = 6)


```

```{r, eval = F}
library(ggtext)
library(colorspace)


elex_map <- counties_sf %>% 
  left_join(elex) %>% 
  mutate(abs_margin2020 = abs(margin2020)) %>% 
  drop_na(margin2020) %>% 
  mutate(margin2020_cat = fct_relevel(margin2020_cat, c("Biden +20%",
                                                        # "Biden +60-80%",
                                                        # "Biden +40-80%",
                                                        "Biden +10-20%", 
                                                        "Biden +0-10%", 
                                                        "Trump +0-10%", 
                                                        "Trump +10-20%",
                                                        # "Trump +40-80%",
                                                        # "Trump +60-80%", 
                                                        "Trump +20%"))) 

tidytemplate::save_it(elex_map)


elex_map %>% 
  ggplot(aes(fill = margin2020_cat)) +
  geom_sf(aes(alpha = abs_margin2020), 
          color = NA)   +
  geom_sf(data = get_urbn_map("states", sf = T), color = "black", inherit.aes = F, fill = NA) +
  theme_void() +
  scale_alpha(range = c(0.5, 1), guide = "none") +
  labs(title = "**Preliminary** Results of US 2020 Election", 
       subtitle = "Note: In many counties votes are still being counted.\n",
       caption = glue::glue("\nSource: New York Times. Last updated: {as.character(elex$retrieved_time)[1]}. Visualization created by @favstats\n")) +
  theme(plot.title = element_markdown(hjust = 0.5, lineheight = 1.2), 
        plot.subtitle = element_text(hjust = 0.5),
        legend.position = "right") + 
  scale_fill_discrete_diverging("Blue-Red 2",
                       name = "Margins") 

tidytemplate::ggsave_it(us2020map_diff, width = 8, height = 6)


```


```{r}
counties_sf %>% 
  left_join(elex) %>% 
  # mutate(abs_margin2020 = abs(margin2020)) %>% 
  ggplot(aes(fill = kanye_perc)) +
  geom_sf(color = NA, na.value = "lightgrey")   +
  geom_sf(data = get_urbn_map("states", sf = T), color = "black", inherit.aes = F, fill = NA, na.value = "lightgrey") +
  scale_fill_gradient("Kanye West Vote Share", 
                       low = "white", 
                       high = "purple", breaks = c(0.25, 0.5, 0.75, 1), labels = c("0.25%", "0.5%", "0.75%"  ,"1%")) +
  theme_void() +
  scale_alpha(range = c(0.75, 1), guide = "none") +
  labs(title = "**Kanye West Vote Share in US 2020 Presidential Election**", 
       subtitle = "Note: In many counties votes are still being counted.\n",
       caption = glue::glue("\nSource: New York Times. Last updated: {as.character(elex$retrieved_time)[1]}. Visualization created by @favstats\n")) +
  theme(plot.title = element_markdown(hjust = 0.5, lineheight = 1.2), 
        plot.subtitle = element_text(hjust = 0.5),
        legend.position = "top") +
  guides(fill = guide_colourbar(direction = "horizontal",
                                label.position = "bottom",
                                barwidth  = 18,
                                barheight = 0.8,  
                                title.vjust = 0.9))

tidytemplate::ggsave_it(kanye_map, width = 8, height = 6)

```




## Analysis / Dataviz

```{r, analysis}


counties_sf %>% 
  left_join(elex) %>% 
  mutate(abs_margin2020 = abs(margin2020)) %>% 
  ggplot(aes(fill = margin2020)) +
  geom_sf(aes(alpha = abs_margin2020), 
          color = NA)   +
  geom_sf(data = get_urbn_map("states", sf = T), color = "black", inherit.aes = F, fill = NA) +
  scale_fill_gradient2("Margins", 
                       low = "#440154FF",
                       mid = "#FDE725FF",
                       high = "#21908CFF",
                       labels = c("+50% Biden", "0%", "+50% Trump"),
                       breaks = c(-50, 0, 50)) +
  theme_void() +
  scale_alpha(range = c(0.75, 1), guide = "none") +
  labs(title = "**Preliminary** Results of US 2020 Election", 
       subtitle = "Note: In many counties votes are still being counted.\n",
       caption = glue::glue("\nSource: New York Times. Last updated: {as.character(elex$retrieved_time)[1]}. Visualization created by @favstats\n")) +
  theme(plot.title = element_markdown(hjust = 0.5, lineheight = 1.2), 
        plot.subtitle = element_text(hjust = 0.5),
        legend.position = "top") +
  guides(fill = guide_colourbar(direction = "horizontal",
                                label.position = "bottom",
                                barwidth  = 18,
                                barheight = 0.8,  
                                title.vjust = 0.9))

tidytemplate::ggsave_it(us2020map_colorblind, width = 8, height = 6)


```

```{r, analysis}


counties_sf %>% 
  left_join(elex) %>% 
  mutate(abs_margin2020 = abs(margin2020)) %>% 
  ggplot(aes(fill = margin2020)) +
  geom_sf(aes(alpha = abs_margin2020), 
          color = NA)   +
  # geom_sf(data = get_urbn_map("states", sf = T), color = "black", inherit.aes = F, fill = NA) +
  scale_fill_gradient2("Margins", 
                       low = "#0000ff", 
                       mid = "purple", 
                       high = "#ff0803",
                       labels = c("+50% Biden", "0%", "+50% Trump"),
                       breaks = c(-50, 0, 50)) +
  theme_void() +
  scale_alpha(range = c(0.75, 1), guide = "none") +
  labs(title = "**Preliminary** Results of US 2020 Election", 
       subtitle = "Note: In many counties votes are still being counted.\n",
       caption = glue::glue("\nSource: New York Times. Last updated: {as.character(elex$retrieved_time)[1]}. Visualization created by @favstats\n")) +
  theme(plot.title = element_markdown(hjust = 0.5, lineheight = 1.2), 
        plot.subtitle = element_text(hjust = 0.5),
        legend.position = "top") +
  guides(fill = guide_colourbar(direction = "horizontal",
                                label.position = "bottom",
                                barwidth  = 18,
                                barheight = 0.8,  
                                title.vjust = 0.9))

tidytemplate::ggsave_it(us2020map_nostateborders, width = 8, height = 6)


```


```{r}
library(tidyverse)

elex %>%
  # filter(eevp >= 90) %>% 
    mutate(results_absentee_trumpd_perc = results_absentee_trumpd/absentee_votes*100,
           results_absentee_bidenj_perc = results_absentee_bidenj/absentee_votes*100)  %>% 
  select(results_absentee_trumpd_perc, results_absentee_bidenj_perc) %>% 
  gather()  %>% 
  mutate(key = case_when(
    key == "results_absentee_trumpd_perc" ~ "% Trump Absentee Votes",
    key == "results_absentee_bidenj_perc" ~ "% Biden Absentee Votes"
  ))  %>% 
  # drop_na(metro) %>% 
  ggplot(aes(key, value)) +
  geom_violin(aes(fill = key), show.legend = F) +
  geom_boxplot(width = 0.2) +
  EnvStats::stat_median_iqr_text() +
  scale_y_continuous(breaks = c(0, 25, 50, 75, 100), label = paste0(c(0, 25, 50, 75, 100), "%")) +
  theme_minimal() +
  labs(x = "\nShare of Votes for Trump vs. Biden", y = "Share of Absentee Votes of all\nAbsentee Votes counted so far (per county)", title = "Share of Absentee Votes cast so far of all Absentee Votes (per county)", subtitle = "Note: Some counties are still counting votes. On average the share of absentee votes per county was\nhigher for Trump than for Biden. Keep in mind that the vast majority of counties are rural and therefore only\nrepresent a small population. The absolute number of absentee votes counted so far is +54m of which\n+29m (54.9%) were cast for Biden and +23m (43.7%) were cast for Trump.\n",
       caption = glue::glue("\n\nSource: New York Times. Last updated: {as.character(elex$retrieved_time)[1]}. Visualization created by @favstats\n")) +
  ggthemes::scale_fill_fivethirtyeight("Results") 
```



```{r}
absentee_dat <-elex %>% 
  select(results_absentee_bidenj,
         results_absentee_trumpd) %>% 
  gather() #

  
absentee_summarized <- elex %>% 
    summarise(results_absentee_trumpd  = sum(results_absentee_trumpd),
              results_absentee_bidenj  = sum(results_absentee_bidenj),
              absentee_votes = sum(absentee_votes)) %>% 
    mutate(results_absentee_trumpd_perc = results_absentee_trumpd/absentee_votes*100,
           results_absentee_bidenj_perc = results_absentee_bidenj/absentee_votes*100) #%>% 
  gather()

absentee_dat %>% 
  mutate(key = case_when(
    key == "results_absentee_trumpd" ~ "Absentee Votes for Trump",
    key == "results_absentee_bidenj" ~ "Absentee Votes for Biden"
  )) %>% 
  ggplot(aes(value, fill = key)) + 
  geom_density(color = NA, alpha = 0.5) +
  scale_x_log10() +
  ggthemes::scale_fill_fivethirtyeight("Results") +
  theme_minimal() +
  labs(x = "\nLogged Number of Absentee Votes", y = "Density", title = "Logged Number of Absentee Ballots counted so far", subtitle = "Note: Some counties are still counting votes.") +
  theme(legend.position = "top")
  geom_text(data = aes(label = value))
```

```{r}
  elex %>% 
    summarise(results_absentee_trumpd  = sum(results_absentee_trumpd),
              results_absentee_bidenj  = sum(results_absentee_bidenj),
              absentee_votes = sum(absentee_votes)) %>% 
    mutate(results_absentee_trumpd_perc = results_absentee_trumpd/absentee_votes*100,
           results_absentee_bidenj_perc = results_absentee_bidenj/absentee_votes*100) %>%
    select(absentee_votes, results_absentee_trumpd, results_absentee_trumpd_perc, results_absentee_bidenj, results_absentee_bidenj_perc) %>% 
    as.list()
```
```{r}
library(ggbeeswarm)

elex_dat <- elex %>% 
  mutate(votes_perc = votes/sum(votes)) %>% 
  mutate(abs_margin2020 = abs(margin2020)) 

elex_dat %>% 
  ggplot(aes(y = margin2020, x= 1, color = margin2020, size = votes_perc, alpha = abs_margin2020)) + 
  # geom_quasirandom(method = "tukeyDense", groupOnX=T) +
  # geom_jitter() +
  # geom_quasirandom(method = "smiley", aes(size = votes)) +
  scale_color_gradient2("Margins", 
                       low = "#0000ff", 
                       mid = "purple", 
                       high = "#ff0803") +
  scale_y_continuous(labels = c("+50% Biden", "0%", "+50% Trump"),
                       breaks = c(-50, 0, 50)) +
  scale_alpha(range = c(0.4, 1)) +
  scale_size(range = c(0.65, 12)) +
  coord_flip() +
  ggthemes::theme_fivethirtyeight() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(y = "\nCounty Margins in the 2020 US Election", caption = glue::glue("\n\nColor reflects by which margin the county was won: blue = greater Biden margin; red = greater Trump margin. The size of the bubble reflects the county share of votes of the national total vote count.\n\nSource: New York Times. Last updated: {as.character(elex$retrieved_time)[1]}. Visualization created by @favstats\n"), title = "US 2020 Presidential Election - Results by County") +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_blank(), plot.caption = element_text(hjust = 0)) 

tidytemplate::ggsave_it(beeswarm, width = 13, height =6)
```

```{r}
# libraries
library(packcircles)
library(ggplot2)
library(viridis)

# Create data
# data <- data.frame(group=paste("Group", letters[1:20]), value=sample(seq(1,100),20)) 


# Generate the layout
packing <- circleProgressiveLayout(elex_dat$margin2020, sizetype='area')
packing$radius <- 0.95*packing$radius
elex_dat <- cbind(elex_dat, packing)
dat.gg <- circleLayoutVertices(packing, npoints=3000)

# dat.gg %>% 
#   cbind()

# Plot 
ggplot() + 
  geom_polygon(data = dat.gg, aes(x, y, group = id, fill=id), colour = "black", alpha = 0.6) +
  scale_fill_viridis() +
  # geom_text(data = elex_dat, aes(x, y, size=value, label = group), color="black") +
  theme_void() + 
  theme(legend.position="none")+ 
  coord_equal()
```
```{r}
elex_dat %>% 
  mutate(vote_size = ifelse(votes >= 100000, "Counties with more than 100k votes", "Counties with less than 100k votes")) %>% 
  # filter(state %in% c("pennsylvania", "georgia", "michigan", "nevada", "minnesota", "arizona")) %>% 
  ggplot(aes(y = margin2020, x= vote_size, color = margin2020, size = votes_perc, alpha = abs_margin2020)) + 
  # geom_beeswarm() +
  geom_quasirandom(method = "tukeyDense", groupOnX=T) +
  # geom_jitter() +
  # geom_quasirandom(method = "smiley", aes(size = votes)) +
  scale_color_gradient2("Margins",
                       low = "#0000ff",
                       mid = "purple",
                       high = "#ff0803") +
  # colorspace::scale_color_discrete_qualitative() +
  scale_y_continuous(labels = c("+50% Biden", "0%", "+50% Trump"),
                       breaks = c(-50, 0, 50)) +
  scale_alpha(range = c(0.4, 1)) +
  scale_size(range = c(0.65, 12)) +
  coord_flip() +
  ggthemes::theme_fivethirtyeight() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(y = "\nCounty Margins in the 2020 US Election", caption = glue::glue("\n\nColor reflects by which margin the county was won: blue = greater Biden margin; red = greater Trump margin. The size of the bubble reflects the county share of votes of the national total vote count.\n\nSource: New York Times. Last updated: {as.character(elex$retrieved_time)[1]}. Visualization created by @favstats\n"), title = "US 2020 Presidential Election - Results by County") +
  facet_wrap(~vote_size, ncol = 1) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_blank(), plot.caption = element_text(hjust = 0)) 

tidytemplate::ggsave_it(beeswarm4, width = 13, height =6)

```

```{r}
elex_dat %>% 
  mutate(vote_size = ifelse(votes >= 100000, "Counties with more than 100k votes", "Counties with less than 100k votes")) %>% 
  mutate(abs_margin2016 = abs(margin2016)) %>% 
    ggplot(aes(y = margin2016, x= vote_size, color = margin2016, size = votes_perc, alpha = abs_margin2016)) + 
  # geom_beeswarm() +
  geom_quasirandom(method = "tukeyDense", groupOnX=T) +
  # geom_jitter() +
  # geom_quasirandom(method = "smiley", aes(size = votes)) +
  scale_color_gradient2("Margins",
                       low = "#0000ff",
                       mid = "purple",
                       high = "#ff0803") +
  # colorspace::scale_color_discrete_qualitative() +
  scale_y_continuous(labels = c("+50% Clinton", "0%", "+50% Trump"),
                       breaks = c(-50, 0, 50)) +
  scale_alpha(range = c(0.4, 1)) +
  scale_size(range = c(0.65, 12)) +
  coord_flip() +
  ggthemes::theme_fivethirtyeight() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(y = "\nCounty Margins in the 2020 US Election", caption = glue::glue("\n\nColor reflects by which margin the county was won: blue = greater Clinton margin; red = greater Trump margin. The size of the bubble reflects the county share of votes of the national total vote count.\n\nSource: New York Times. Last updated: {as.character(elex$retrieved_time)[1]}. Visualization created by @favstats\n"), title = "US 2020 Presidential Election - Results by County") +
  facet_wrap(~vote_size, ncol = 1) +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_blank(), plot.caption = element_text(hjust = 0)) 

tidytemplate::ggsave_it(beeswarm_2012, width = 13, height =4)

```

